config/routes.rb
Fsd::Application.routes.draw do

  root :to => 'lessons#index'

  match 'lessons/:id/addVideo' => 'lessons#addVideo'

  match 'lessons/:id/setsize' => 'lessons#setsize'

  match 'lessons/reorder' => 'lessons#reorder'

  scope '/auth' do
    match '/admin', :as => :login
    match '/admin/callback', :to => 'sessions#authenticate_admin'
    match '/failure', :to => 'sessions#admin_authentication_failure'
    match '/admin/logout', :to => 'sessions#logout_admin', :as => :logout
  end

  resources :lessons do
    resources :prezis, :documents, :videos, :comments do
      collection do
        post "sort"
        end
    end
    collection do
      post "sort"
    end
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :lesson
  
  validates_presence_of :title
  
  def self.sublesson(page,size)
    
  end
 
   
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_filter :admin_required, :except => [:create]

  # def new
    # @lesson = Lesson.title(params[:lesson_id])
  # end

  def create
    @lesson = Lesson.find(params[:lesson_id])
    begin
      @comment = @lesson.comments.create!(params[:comment])
    rescue
      flash[:notice] = "You must enter a title for comment."
    end
    redirect_to lesson_path(@lesson)
  end

  def edit
    @user = session[:admin_user]
    @lesson = Lesson.find(params[:lesson_id])
    begin
      @comment = Comment.find(params[:id])
    rescue
      flash[:notice] = "Comment not found."
      redirect_to lesson_path(@lesson)
    end
  end

  def update
    @lesson = Lesson.find(params[:lesson_id])
    @comment = Comment.find params[:id]
    begin
      @comment.update_attributes!(params[:comment])
      flash[:notice] = "#{@comment.title} was successfully updated."
      redirect_to lesson_path(@lesson)
    rescue
      flash[:notice] = "You must enter a title for comment."
      redirect_to edit_lesson_comment_path(@comment)
    end
  end

  def destroy
    @lesson = Lesson.find(params[:lesson_id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    flash[:notice] = "Comment '#{@comment.title}' deleted."
    redirect_to lesson_path(@lesson)
  end
end

app/views/comments/_comment.html.haml
#comment
  %h2= comment.title
  by #{comment.editor} on #{comment.created_at}
  -if admin?
    .right
      = link_to "moderate comment", edit_lesson_comment_path(comment.lesson_id, comment.id)
    .clear
  %hr
  %p= comment.body
 

app/views/comments/_comment_feed.html.haml
%hr
%h2 Comments
- if @currentpage.to_i != 1
  = link_to "<< Previous Page", lesson_path(@lesson, :page => (@currentpage.to_i-1))
- if ((@totalpage.to_i != 0) and (@currentpage.to_i != @totalpage.to_i))
  .right= link_to "Next Page >>", lesson_path(@lesson, :page => (@currentpage.to_i+1))
.clear
%br
- @comments.each do |comment|
  = render :partial => 'comments/comment', :locals => { :comment => comment }
- if !@comments.empty?
  %br
- if @currentpage.to_i != 1
  = link_to "<< Previous Page", lesson_path(@lesson, :page => (@currentpage.to_i-1))
  %br
- if ((@totalpage.to_i != 0) and (@currentpage.to_i != @totalpage.to_i))
  .right= link_to "Next Page >>", lesson_path(@lesson, :page => (@currentpage.to_i+1))
  %br
.clear
= render :partial => "comments/comment_form"

app/views/comments/_comment_form.html.haml
= form_tag url_for(:controller => "comments", :action => "create", :lesson_id => @lesson.id) do
  = label :comment, :title, 'Title'
  %br
  = text_field :comment, 'title'
  %br
  = label :comment, :editor, 'Author'
  %br
  = text_field :comment, 'editor'
  %br
  = label :comment, :body, 'Comment'
  %br
  = text_area :comment, 'body'
  %br
  %br
  = submit_tag 'Submit Comment'

app/views/comments/edit.html.haml
#wrapper
  = render :partial => "shared/head"
  #main
    .content
      %h1 Edit Comment
      %hr
      - if flash[:notice] != nil
        #notice.message= flash[:notice]
        %br
      - elsif flash[:warning] != nil
        #warning.message= flash[:warning]
        %br
      = form_tag lesson_comment_path(@comment.lesson_id, @comment.id), :method => :put do
        = label :comment, :title, 'Title'
        %br
        = text_field :comment, 'title'
        %br
        = label :comment, :editor, 'Author'
        %br
        = text_field :comment, 'editor'
        %br
        = label :comment, :body, 'Comment'
        %br
        = text_area :comment, 'body'
        %br
        %br
        = submit_tag 'Save Changes'
        %br
  #right_sidebar
    .content
      -if !@user.nil?
        %h2 admin control panel
        %p
          = link_to "Delete Comment", lesson_comment_path(@comment.lesson_id, @comment.id), :method => :delete, :confirm => 'Are you sure?'
          %br
          = link_to "Logout", logout_path
        %hr
      %h2 navigation
      %p= link_to "Return Home", root_path
  .clear
  = render :partial => "shared/footer"