config/routes.rb
Fsd::Application.routes.draw do

  root :to => 'lessons#index'

  match 'lessons/:id/addVideo' => 'lessons#addVideo'

  match 'lessons/:id/setsize' => 'lessons#setsize'

  match 'lessons/reorder' => 'lessons#reorder'

  scope '/auth' do
    match '/admin', :as => :login
    match '/admin/callback', :to => 'sessions#authenticate_admin'
    match '/failure', :to => 'sessions#admin_authentication_failure'
    match '/admin/logout', :to => 'sessions#logout_admin', :as => :logout
  end

  resources :lessons do
    resources :prezis, :documents, :videos, :comments do
      collection do
        post "sort"
        end
    end
    collection do
      post "sort"
    end
  end

end

app/views/shared/_footer.html.haml
#footer
   .float
      .content 
         %h2 Find Us Online
         = link_to 'facebook', 'https://www.facebook.com/foundation.for.sustainable.development'
         %br
         = link_to 'twitter', 'http://twitter.com/#!/infoFSD'
         %br
         = link_to 'youtube', 'http://www.youtube.com/fsdinternational'
         %br
         = link_to 'linkedin', 'http://www.linkedin.com/groups?gid=111574&mostPopular=&trk=tyah'
         %br
         = link_to 'fsd home', 'http://fsdinternational.org/'
         %br
         %br
         = link_to "admin login", login_path
   .float
      .content
         %h2 Contact Us
         = link_to 'info@fsdinternational.org', 'mailto:info@fsdinternational.org'
         %br
         %br
         1000 Brannan St, Suite 207
         %br
         San Francisco, CA 94103
   .float
      .content
         %h2 What You Can Do
         = link_to 'programs abroad', 'http://fsdinternational.org/trainingprograms'
         %br
         = link_to 'giving circle', 'http://fsdinternational.org/givingcircle'
         %br
         = link_to 'donate', 'http://fsdinternational.org/donate'
   .float
      .content
         %h2 About FSD
         FSD reduces global poverty by providing over 300 grassroots community organizations around the world with training and key resources to address pressing socioeconomic issues.
   .clear
   %br
   %img{:src => '/assets/featuredin.png'}

app/views/shared/_head.html.haml
#header
  = link_to image_tag('/assets/logo.gif'), 'http://fsdinternational.org'
  = link_to image_tag('/assets/donatemap_orange.png', :id => 'donate'), 'https://fsdinternational.secure.force.com/donation'
  = link_to image_tag('/assets/facebook-logo.png', :class => 'sm_button'), 'http://www.facebook.com/Foundation.for.Sustainable.Development'
  = link_to image_tag('/assets/twitlogo.png', :class => 'sm_button'), 'http://twitter.com/#!/infoFSD'
  = link_to image_tag('/assets/youtubelogo.png', :class => 'sm_button'), 'http://www.youtube.com/user/FSDInternational'
  = link_to image_tag('/assets/linkedin-logo.png', :class => 'sm_button'), 'http://www.linkedin.com/groupInvitation?groupID=111574&sharedKey=78062C18E873&goback=%2Esrp_1_1213183747021_in'
  .clear

app/views/shared/_navigation.html.haml
#left_sidebar
  -if !@user.nil?
    %h2 Admin Control Panel
    .navlink= link_to "Create Lesson", new_lesson_path
    .navlink= link_to "Edit Lesson", edit_lesson_path(@lesson)
    .navlink= link_to "Delete Lesson", lesson_path(@lesson), :method => :delete, :confirm =>'Are you sure?'
    .navlink= link_to "Upload Prezi", new_lesson_prezi_path(@lesson)
    .navlink= link_to "Upload Video", new_lesson_video_path(@lesson)
    .navlink= link_to "Upload Document", new_lesson_document_path(@lesson)
    .navlink= link_to "Logout", logout_path
    %br
  %h2 Navigation
  - if !@lessons.empty?
    #lessons_nav
      - @lessons.each do |lesson|
        - if @lesson == lesson
          .navlink_highlighted= link_to "#{lesson.title} >>", lesson_path(lesson)
        - else
          .navlink= link_to "#{lesson.title}", lesson_path(lesson)
  .navlink= link_to "Return to Resource Center Home", root_path
  %br

app/views/shared/_navigation_edit.html.haml
#left_sidebar
  .content
    -if !@user.nil?
      %h2 Admin Control Panel
      .navlink= link_to "Logout", logout_path
      %br
    %h2 Navigation
    .navlink= link_to "Return to Lesson", lesson_path(@lesson)
    .navlink= link_to "Return to Resource Center Home", root_path
    %br

app/views/shared/_navigation_new.html.haml
#left_sidebar
  .content
    -if !@user.nil?
      %h2 Admin Control Panel
      .navlink= link_to "Logout", logout_path
    %h2 Navigation
    .navlink= link_to "Return to Resource Center Home", root_path
    %br

app/views/shared/_navigation_reorder.html.haml
#left_sidebar
  .content
    -if !@user.nil?
      %h2 Admin Control Panel
      .navlink= link_to "Logout", logout_path
      %br
    %h2 Navigation
    .navlink= link_to "Return to Lesson", lesson_path(@lesson_id)
    .navlink= link_to "Return to Resource Center Home", root_path
    %br

app/views/shared/_reorder_components.html.haml
#wrapper
  = render :partial => "shared/head"
  = render :partial => "shared/navigation_reorder"
  #main
    .content
      %h1 Reorder #{component}
      - if flash[:notice] != nil
        %br
        #notice.message= flash[:notice]
      - elsif flash[:warning] != nil
        %br 
        #warning.message= flash[:warning]
      %table
        %thead
          %tr.title 
            %th.title= "#{component}"
                  
        %tbody#components
          - if components.empty?
            %tr 
              %td= "There currently no #{component} available for this lesson." 
          - else
            - components.each do |component|
              %tr{:class => "lessons", :id=> "#{component.id}"}
                %td.lessons= "#{component.title}"      
  .clear
  %br
  = render :partial => "shared/footer"

- content_for :head do  
  %script{:charset => "utf-8", :type => "text/javascript"}
    $(document).ready(function() {
    $('#components').tableDnD({
    onDrop: function(table, row){
    $.ajax({
    type: "POST",
    url: "#{url_for(:action => 'sort')}",
    processData: false,
    data: $.tableDnD.serialize() + '&authenticity_token=' + encodeURIComponent("#{form_authenticity_token if protect_against_forgery?}")
       
    });
    }  
    });
    });