config/routes.rb
Fsd::Application.routes.draw do

  root :to => 'lessons#index'

  match 'lessons/:id/addVideo' => 'lessons#addVideo'

  match 'lessons/:id/setsize' => 'lessons#setsize'

  match 'lessons/reorder' => 'lessons#reorder'

  scope '/auth' do
    match '/admin', :as => :login
    match '/admin/callback', :to => 'sessions#authenticate_admin'
    match '/failure', :to => 'sessions#admin_authentication_failure'
    match '/admin/logout', :to => 'sessions#logout_admin', :as => :logout
  end

  resources :lessons do
    resources :prezis, :documents, :videos, :comments do
      collection do
        post "sort"
        end
    end
    collection do
      post "sort"
    end
  end

end

app/models/lesson.rb
class Lesson < ActiveRecord::Base

  has_many :videos
  has_many :documents
  has_many :prezis
  has_many :comments

  validates_presence_of :title

  before_save { |lesson| lesson.position = Lesson.next_position()}

  def self.title(id)
    Lesson.find(id).title
  end

  def self.next_position()
    if Lesson.all.empty?
      return 0
    else
      return Lesson.order(:position).last.position + 1
    end
  end
  
  def self.sublessons(page,size)
    
  end

end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController

  before_filter :admin_required, :except => [:index, :show]

  def show
    @lessons = Lesson.order(:position)
    @user = session[:admin_user]
    banners = ["banner1.jpg", "banner2.jpg", "banner3.jpg", "banner4.jpg", "banner5.jpg", "banner6.jpg", "banner7.jpg", "banner8.jpg"]
    random = rand(8)
    @banner = banners[random]
    id = params[:id] # retrieve lesson ID from URI route

    begin
      @lesson = Lesson.find(id) # look up lesson by unique ID

      @documents = @lesson.documents.order(:position)

      @prezis = @lesson.prezis.order(:position)

      @videos = @lesson.videos.order(:position)

      allcomments = @lesson.comments

      @totalpage = (allcomments.length/15.to_f).ceil

      @currentpage = params[:page]

      if @currentpage == nil
        @currentpage = 1
        @comments = allcomments[0,15]
      elsif @currentpage.to_i > 0 and @currentpage.to_i <= @totalpage.to_i
        @comments = allcomments[(@currentpage.to_i-1)*15,15]
      else
        @currentpage = 1
        @comments = allcomments[0,15]
        flash[:notice] = "Comment page out of range."
      end

    rescue Exception => e
      puts e.message
      flash[:notice] = "Lesson not found."
      redirect_to lessons_path
    end
    # will render app/views/lessons/show.<extension> by default
  end

  def index
    @user = session[:admin_user]
    banners = ["banner1.jpg", "banner2.jpg", "banner3.jpg", "banner4.jpg", "banner5.jpg", "banner6.jpg", "banner7.jpg", "banner8.jpg"]
    random = rand(8)
    @banner = banners[random]
    @lessons = Lesson.order(:position)
  end

  def new
    @user = session[:admin_user]
    # default: render 'new' template
  end

  def create
    @lesson = Lesson.new(params[:lesson])
    if @lesson.save and !@lesson.title.blank?
      flash[:notice] = "#{@lesson.title} was successfully created."
      redirect_to lessons_path
    else
      flash[:notice] = "You must enter a title for lesson."
      redirect_to new_lesson_path
    end
  end

  def edit
    @user = session[:admin_user]
    begin
      @lesson = Lesson.find(params[:id])
    rescue
      flash[:notice] = "Lesson not found."
      redirect_to lessons_path
    end
  end

  def update
    @lesson = Lesson.find params[:id]
    begin
      @lesson.update_attributes!(params[:lesson])
      flash[:notice] = "#{@lesson.title} was successfully updated."
      redirect_to lesson_path(@lesson)
    rescue
      flash[:notice] = "You must enter a title for lesson."
      redirect_to edit_lesson_path(@lesson)
    end
  end

  def destroy
    @lesson = Lesson.find(params[:id])
    @lesson.destroy
    flash[:notice] = "Lesson '#{@lesson.title}' deleted."
    redirect_to lessons_path
  end

  def sort
    params["lessons"].each_with_index { |id, index|
        lesson = Lesson.find(id.to_i)
        lesson.position = index
        lesson.save
      }

    render :nothing => true
  end

  def reorder
    @user = session[:admin_user]
    @lessons = Lesson.order(:position)
  end

end

app/views/lessons/edit.html.haml
#wrapper
  = render :partial => "shared/head"
  = render :partial => "shared/navigation_edit"
  #main
    .content
      %h1 Edit Lesson
      %hr
      - if flash[:notice] != nil
        #notice.message= flash[:notice]
        %br
      - elsif flash[:warning] != nil
        #warning.message= flash[:warning]
        %br
      = form_tag lesson_path(@lesson), :method => :put do
        = label :lesson, :title, 'Title'
        %br
        = text_field :lesson, 'title'
        %br
        %br
        = label :lesson, :description, 'Description'
        %br
        = text_area :lesson, 'description'
        %br
        %br
        = submit_tag 'Save Changes'
  .clear
  = render :partial => "shared/footer"

app/views/lessons/index.html.haml
#fb-root
:javascript
   (function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
      fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));

#wrapper
   = render :partial => "shared/head"
   .content
      %img{:src => "/assets/#{@banner}"}
      %h1 Welcome to the FSD Resource Center
      - if flash[:notice] != nil
         #notice.message= flash[:notice]
      - elsif flash[:warning] != nil
         #warning.message= flash[:warning]
      #left_sidebar
         - if !@user.nil?
            %h2 Admin Control Panel
            .navlink= link_to "Create Lesson", new_lesson_path
            .navlink= link_to "Reorder Lessons", lessons_reorder_path
            .navlink= link_to "Logout", logout_path
            %br
         %h2 Facebook
         .fb-like-box{"data-border-color" => "#c2ad99", "data-header" => "false", "data-height" => "300", "data-href" => "http://www.facebook.com/Foundation.for.Sustainable.Development", "data-show-faces" => "true", "data-stream" => "true", "data-width" => "225"}
         %br
         %br
         %br
         %hr
         %h2 Twitter
         %script{:charset => "utf-8", :src => "http://widgets.twimg.com/j/2/widget.js"}
         :javascript
            new TWTR.Widget({
               version: 2,
               type: 'profile',
               rpp: 5,
               interval: 30000,
               width: 225,
               height: 200,
               theme: {
                  shell: {
                     background: '#c2ad99',
                     color: '#000000'
                  },
                  tweets: {
                     background: '#f2eeda',
                     color: '#000000',
                     links: '#e37226'
                  }
               },
               features: {
                  scrollbar: true,
                  loop: false,
                  live: true,
                  behavior: 'all'
               }
            }).render().setUser('infoFSD').start();
         %br
      #main
         %p FSD reduces global poverty by providing over 300 grassroots community organizations around the world with training and key resources to address pressing socioeconomic issues.
         %p The FSD Resource Center is an online e-learning center that provides pre-departure training online for university students and young professionals. Documents, presentations, and videos are organized by lesson to create a classroom-like experience.
         %table
            %thead
               %tr.title 
                  %th.title Lessons
            %tbody#lessons
               - if @lessons.empty?
                  %tr 
                     %td There currently no lessons available. Please check back later.
               - else
                  - @lessons.each do |lesson|
                     %tr{:class => "lessons", :id=> "#{lesson.id}"}
                        %td.lessons= link_to "#{lesson.title} >>", lesson_path(lesson)  
         %br
   .clear

   = render :partial => "shared/footer"

app/views/lessons/new.html.haml
#wrapper
  = render :partial => "shared/head"
  = render :partial => "shared/navigation_new"
  #main
    .content
      %h1 Create a New Lesson
      %hr
      - if flash[:notice] != nil
        #notice.message= flash[:notice]
        %br
      - elsif flash[:warning] != nil
        #warning.message= flash[:warning]
        %br
      = form_tag lessons_path do
        = label :lesson, :title, 'Title'
        %br
        = text_field :lesson, 'title'
        %br
        %br
        = label :lesson, :description, 'Description'
        %br
        = text_area :lesson, 'description'
        %br
        %br
        = submit_tag 'Save Changes'
  .clear
  = render :partial => "shared/footer"

app/views/lessons/reorder.html.haml
#wrapper
  = render :partial => "shared/head"
  = render :partial => "shared/navigation_new"
  #main
    .content
      %h1 Reorder Lessons
      - if flash[:notice] != nil
        %br
        #notice.message= flash[:notice]
      - elsif flash[:warning] != nil
        %br 
        #warning.message= flash[:warning]
      %table
        %thead
          %tr.title 
            %th.title Lessons
        %tbody#lessons
          - if @lessons.empty?
            %tr 
              %td There currently no lessons available. Please check back later.
          - else
            - @lessons.each do |lesson|
              %tr{:class => "lessons", :id=> "#{lesson.id}"}
                %td.lessons #{lesson.title}    
  .clear
  %br
  = render :partial => "shared/footer"

- content_for :head do  
  %script{:charset => "utf-8", :type => "text/javascript"}
    $(document).ready(function() {
    $('#lessons').tableDnD({
    onDrop: function(table, row){
    $.ajax({
    type: "POST",
    url: "#{url_for(:action => 'sort')}",
    processData: false,
    data: $.tableDnD.serialize() + '&authenticity_token=' + encodeURIComponent("#{form_authenticity_token if protect_against_forgery?}")
       
    });
    }  
    });
    });

app/views/lessons/show.html.haml
#wrapper
  = render :partial => "shared/head"
  .content
    .content
      %img{:src => "/assets/#{@banner}"}
      %h1= @lesson.title
      - if flash[:notice] != nil
        #notice.message= flash[:notice]
      - elsif flash[:warning] != nil
        #warning.message= flash[:warning]
    = render :partial => "shared/navigation"
    #main
      %h2 Description
      %p= @lesson.description
      %hr
      - if @prezis.empty? and @videos.empty? and @documents.empty?
        %p There are no prezis, videos, or documents uploaded to this lesson.   
      - if not @prezis.empty?    
        #prezis
          %h2 Prezis
          - if !@user.nil?
            = link_to "Reorder Prezis", lesson_prezis_path(@lesson.id)
          - @prezis.each do |prezi|
            = render :partial => 'prezis/prezi_player', :locals => {:url => prezi.url}
            - if !@user.nil?
              %br
              = link_to "Delete Prezi", lesson_prezi_path(@lesson.id, prezi.id), :method => :delete, :confirm => 'Are you sure?' 
              %br
              %br
      - if not @videos.empty?
        #videos
          %h2 Videos
          - if !@user.nil?
            = link_to "Reorder Videos", lesson_videos_path(@lesson.id)
            %br
          - @videos.each do |video|
            = render :partial => 'videos/youtube_video', :locals => { :url => video.url }
            -if !@user.nil?
              %br
              = link_to "Delete Video", lesson_video_path(@lesson.id, video.id), :method => :delete, :confirm =>'Are you sure?'
              %br
              %br
      - if not @documents.empty?
        #documents
          %h2 Documents
          - if !@user.nil?
            = link_to "Reorder Documents", lesson_documents_path(@lesson.id)
          - @documents.each do |doc|
            = render :partial => 'documents/doc_iframe', :locals => { :url => doc.url}
            -if !@user.nil?
              %br
              = link_to "Delete Document", lesson_document_path(@lesson.id, doc.id), :method => :delete, :confirm => 'Are you sure?'
              %br
              %br
      #comments
        = render :partial => "comments/comment_feed"
  .clear
  = render :partial => "shared/footer"